### PR TITLE
fix: pasting image not update value bug

### PR DESCRIPTION
**Pull request by xwchris**
There is a bug when paste an image using custom `imageUploadFunction` to upload image. The value will not update after uploading image successfully. I add some code try to update value when image update successfully. I tested it in my code and the result is right now!

### CODE REVIEW

**Comment by xwchris** [comment]
@RIP21 may you look at this

**Comment by RIP21** [comment]
I'm not sure why you can't implement that using `options` props right now. Why it should get into the internals of the component.

**Comment by RIP21** [comment]
@btzr-io what do you think. Does it makes sense? Because I don't understand why it's needed.

**Comment by btzr-io** [comment]
@xwchris Why do you need the upload image function ? can you provide a more detailed explanation or some code to see how are you adding the image ?

**Comment by xwchris** [comment]
@RIP21 @btzr-io

**Comment by xwchris** [comment]
@RIP21 @btzr-io 

I used `imageUploadFunction` in `options` to implement uploading image. But there is a bug, after pasting an image. Through the editor show the image url in the content, the value in `react-simplemde-editor` not update at all.

This is my implement.
image

After pasting image, let's see the result when success.
image

From this image, you can see the value not change after image uploading successfully. This is because uploading is an async process and `react-simplemde-editor` not update the value after uploading finish.

so I add this to update value after uploading successfully.
image

The result is right now
image

**Comment by RIP21** [comment]
Ah ok. It starts to make sense.  @btzr-io what do you think?
I looked at the source code of easymde and I don't see any other way to achieve this async behavior. There is no events or something special triggered after upload success to do it in a different way than this way.

Although double-check it
https://github.com/Ionaru/easy-markdown-editor/blob/master/src/js/easymde.js

If you feel it makes sense too. Then I think we will merge it and I'll publish the fixed version.

**Comment by btzr-io** [comment]
@RIP21 Looks good to me

**Comment by btzr-io** [comment]
@RIP21 Looks good to me

**Comment by btzr-io** [comment]
Looks like the only thing that gets notify is the is the status-bar text
https://github.com/Ionaru/easy-markdown-editor/blob/531a0e622746d49769224a44bba1a41d1ac4d8e8/src/js/easymde.js#L808-L819
```js
function afterImageUploaded(editor, url) {
    var cm = editor.codemirror;
    var stat = getState(cm);
    var options = editor.options;
    var imageName = url.substr(url.lastIndexOf('/') + 1);
    _replaceSelection(cm, stat.image, options.insertTexts.uploadedImage, url);
    // show uploaded image filename for 1000ms
    editor.updateStatusBar('upload-image', editor.options.imageTexts.sbOnUploaded.replace('#image_name#', imageName));
    setTimeout(function () {
        editor.updateStatusBar('upload-image', editor.options.imageTexts.sbInit);
    }, 1000);
}
```

**Comment by RIP21** [comment]
4.1.3 released

**Pull request merged**
