### PR TITLE
Added cursorActivity event and made getCursor and getMdeInstance prop.

### PR DESCRIPTION
**Pull request by gjvpaet**
A feature which you can track the current position of the cursor as you move through the editor. I also made a prop for getting the instance of simplemde so the user can use codemirror APIs. This is very useful in certain use cases. This solves issues #59 and #60. I hope this feature gets merged, thanks!

### CODE REVIEW

**Comment by RIP21** [comment]
LGTM.
Unfortunately, I missed the notification. Please mention me or add as a reviewer next time.
Also, I still don't have an access to the module in npm, so I can't just deploy new changes :( 

@benrlodge hey man :D Give me an access to publishing new version :D

**Comment by gjvpaet** [comment]
@RIP21 noted! Thanks for merging! 🎉🎉

**Comment by benrlodge** [comment]
Hey @RIP21, I added you as an owner to the project a while back. Can you not publish? Can you try again? `npm owner ls` within the project shows you:

```
rip21 <puha212@gmail.com>
mrlodge <benrlodge@gmail.com>
```

**Comment by RIP21** [comment]
@benrlodge lool. I didn't got any notifications. Thanks a lot, it should work just fine :)

**Comment by ajish** [comment]
@RIP21 @gjvpaet Is this published to npm? I added 3.6.11 to my package.json, but after yarn install I couldn't find the function `getMdeInstance` in the src folder. It works when I do:
`"react-simplemde-editor": "git://github.com/RIP21/react-simplemde-editor.git#master",`

Another thing I noticed was that the component breaks if I don't pass `getMdeInstance` and `getLineAndCursor` as options, maybe have some defaultProps in your component?

**Comment by RIP21** [comment]
@ajish no it wasn't deployed. I will deploy tomorrow if you're interested. Hope it will not break anything :)

**Comment by ajish** [comment]
@RIP21 yes please, that would make my life easier!
BTW by breaking I meant that `getMdeInstance` and `getLineAndCursor` have now become compulsory props, you have to pass some value to them, otherwise the component won't work.

**Comment by gjvpaet** [comment]
@RIP21 I submitted a PR #63 that addresses @ajish's issue with the props.

**Comment by RIP21** [comment]
@gjvpaet thanks. Merged.
@ajish I will deploy new version soon.

**Comment by RIP21** [comment]
@gjvpaet @ajish new version is deployed. Please tell me if you have any issues with it.
`3.6.12`

I will try to spend some time this weekend to improve this thing significantly.
The new demo, React 16 support, better build that will significantly reduce the bundle size of it etc,

**Comment by RIP21** [comment]
@gjvpaet @ajish actually I already some stuff.
Please test `3.6.13` :)

**Comment by ajish** [comment]
Thank you @RIP21 .
I see that you have removed react as a dependency, makes sense, since this is a wrapper component for another module, so one would expect react to be already present.
Still, maybe add react>(14 or 15) as peer dependency in package.json, to show that react below that won't be supported, just a thought.

**Pull request merged**
